### PR TITLE
Metrica Province route

### PR DESCRIPTION
**Pull request by ghost**
Followed Lulle's route, this time with a more speedrun state of mind.

Hopefully it's up to par with the others.

Feedback appreciated.

### CODE REVIEW

**Comment by Icy1-0-6** [comment]
Ran this route, its pretty good tbh. Clear notes with hearts and personally like the notes when you waypoint back and it tells you what is route 1-2-3 etc.

**Comment by ideka** [comment]
@Icy1-0-6 
> personally like the notes when you waypoint back and it tells you what is route 1-2-3 etc.

Have you been using follow mode? I'll most likely remove those notes because I don't think they are necessary at all in follow mode.

**Comment by ghost** [comment]
> Have you been using follow mode? I'll most likely remove those notes because I don't think they are necessary at all in follow mode.

I didn't even know there was a follow mode until you told me specifically and have been using it since, have stopped using the "first path" etc for waypoints as it was mostly there because I followed the routes in "edit mode".

Dredgehaunt Cliffs i did a pull request for doesn't have it.

**Comment by ghost** [comment]
I could do a new pull request for this route with a json that has the text removed.

**Comment by Icy1-0-6** [comment]
wasnt using follow mode(not sure how i use it).

**Comment by ghost** [comment]
> wasnt using follow mode(not sure how i use it).

https://www.reddit.com/r/AugmentedTyria/comments/6oxyhu/augmented_tyria_release_02beta/

1. Load into map
2. Press "/" to load route for current map
3. Press numpad period to initiate follow mode 
4. Press numpad 0 to toggle direction helper.

Reaching a node "consumes it" copying its text to the clipboard (useful for WP nodes). So when you teleport back to a WP there's only one node showing you where to go, even if that one WP has several paths connected to it and the directional helper has a green line spanning from your character to next node so you always know where to go immedietly after WPing.

**Comment by Icy1-0-6** [comment]
Ah was still running the 0.1 version, updated now, running all routes with follow now

**Comment by ghost** [comment]
Updated the path to no longer contain any "first path/second path" text.

**Pull request merged**
