### PR TITLE
Wayfarer foothills route

### PR DESCRIPTION
**Pull request by ghost**
Followed Lulle's route.

### CODE REVIEW

**Comment by Ryaden** [comment]
I ran Wayfarer with this file and it worked perfectly. Nice explanations at heart points too.

**Comment by ideka** [comment]
I'll check it out soon.

I assume @Queezi you are /u/ChiliFajita on reddit.

Only problem is, the Wayfarer Foothills route was assigned to @Ryaden [here](https://www.reddit.com/r/AugmentedTyria/comments/5yvnfo/route_making_progress/).

What happened?

I'll get to reviewing the route soon.

**Comment by Ryaden** [comment]
It's fine by me if this one is used instead. It's the same route as mine. I'll stop with my version then.

**Comment by ghost** [comment]
@ideka yeah thats my reddit profile.

I'm sorry if this was in conflict to anything previously decided. I just made a new character and will be making routes for all the maps I come across that do not yet have one in the latest master commit.

**Comment by ideka** [comment]
It took me a long time to really make the route be on par with the other ones.

I've prepared a sort of "comparer" build. All it does is show two routes at the same time. [You can find it here](https://www.dropbox.com/s/jx4n1nehos7sdeh/AugTyrComparer.zip?dl=0). It's loaded with the route you gave me along with the result after I reviewed it.

If you want to continue cotributing routes, *please* study and incorporate the differences.

**Comment by ghost** [comment]
Looked it over and got the message, more efficency.

I did my routes while actually doing the map exploration and so I plotted the "natural" movement through hearts (which is where most of the big differences lies).

You don't have to go over the last pull requests I did as I will go over them in a day or two.

**Comment by ideka** [comment]
> Looked it over and got the message, more efficency.

Yes, that's a big part of it.

> I did my routes while actually doing the map exploration and so I plotted the "natural" movement through hearts (which is where most of the big differences lies).

I get that. Policy for routing most hearts right now is mostly just connect the heart node to the heart wall node with the fastest possible route between them. The reason is that heart completion is not very reliable most of the time and depends on highly unpredictable stuff like the position of enemies and such. Route followers are meant to freely move away from the route as they see fit to complete the hearts efficiently.

Exceptions are hearts that have true and tested methods to completing them, and that literally involve following a set route. E.g. the last heart in this very map.

> You don't have to go over the last pull requests I did as I will go over them in a day or two.

Thanks!

**Pull request merged**
