### PR TITLE
Cursed shore+Malchors leap + Frostgorge sound + Sparkfly Fen

### PR DESCRIPTION
**Pull request by Icy1-0-6**
Made as per the guide. Polished some jumps and text.

### CODE REVIEW

**Comment by ideka** [comment]
I'll get to reviewing this eventually. I fear route reviews can take me a really long time to do, and I want to focus on getting features done right now.

**Comment by Icy1-0-6** [comment]
Added Malchors leap

**Comment by ghost** [comment]
Will run malechors leap later.

**Comment by Icy1-0-6** [comment]
Frostgorge Sound added

**Comment by Icy1-0-6** [comment]
Sparkfly fen added

**Comment by ghost** [comment]
Started running Malechors Leap and wasn't that impressed, have started ironing it out.

**Comment by ghost** [comment]
I also already did a pull request for a polished version of Frostgorge Sound

**Comment by Icy1-0-6** [comment]
Yea the routes i add are very basic(mainly make them for personal use), I just trow them on here so people can use them, to polish to their liking,. Dont have the patience to make them perfect generally, but they do cover all spots on the map(for me personally the most important). 😛

**Pull request merged**
